apiVersion: v1
kind: Service
metadata:
  name: users-detail
  labels:
    name: users-detail
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    component: users-details